config/routes.rb
SistemaPagos::Application.routes.draw do
  resources :users

  root :to => "Alumnos#index"

  resources :cargos

  resources :pagos

  resources :alumno_costos

  resources :cargo_tipos

  resources :alumnos

  resource  :user_session, :only => [:new, :create, :destroy]

  delete "logout" => "user_sessions#destroy", :as => :logout

  match "sign_in" => "user_sessions#new", :as => :signin

  get "alumno/nuevo" => "alumnos#nuevo", :as => :nuevo_alumno

  post "alumno/crear" => "alumnos#crear", :as => :crear_alumno

  match "alumnos/cargo/:id" => "alumno_costos#index", :as => :cargo_alumnos

end

app/models/alumno.rb
class Alumno < ActiveRecord::Base
  attr_accessible :nombre
  
  has_many :alumno_costos, :foreign_key => "alumno_id", :dependent => :destroy
  has_many :cargos, :foreign_key => "alumno_id", :dependent => :destroy
  validate :nombre, :presence => true, :length => {:within => 5..60}
  default_scope :order => 'alumnos.nombre ASC'
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  # GET /alumnos
  # GET /alumnos.json
  def index
    @cargotipos = CargoTipo.all
    @alumnos = Alumno.all

    #verifica que la fecha no se pase para efectuar el cargo de colegiatura para los alumnos
    fecha_actual = Time.now #Se obtiene fecha actual
    dia_de_cargo = 2 #Se indica que el dia de generación será el dia 2
    @cargo = CargoTipo.find_by_titulo("Colegiatura")
    @alumno_costos = AlumnoCosto.includes(:alumno).order("alumnos.nombre ASC").where(:cargo_tipo_id => @cargo.id)
    #if fecha_actual.day >= dia_de_cargo
    if fecha_actual.day >= dia_de_cargo
      @cargos = Cargo.where('extract(month from fecha) = ?', fecha_actual.month)
      print @cargos
      if @cargos.empty?
        @cargo = CargoTipo.find_by_titulo("Colegiatura")
        @alumno_costos = AlumnoCosto.includes(:alumno).order("alumnos.nombre ASC").where(:cargo_tipo_id => @cargo.id)
        @alumno_costos.each do |alumno_costo|
          @cargo = Cargo.new
          @cargo.fecha = Time.now
          @cargo.alumno_id = alumno_costo.alumno_id
          @cargo.cantidad = alumno_costo.cantidad
          @cargo.tipo_cargo_id = alumno_costo.cargo_tipo_id
          @cargo.save
        end
      else
        print "Ya existe cargo de este mes y no debe realizarse"
      end
    else
      print "No realizar cargo"
    end
    ############################################################################################

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alumnos }
    end
  end

  # GET /alumnos/1
  # GET /alumnos/1.json
  def show
    @alumno = Alumno.find(params[:id])
    @alumno_costos = AlumnoCosto.where(:alumno_id => params[:id])
    @cargo_tipos = CargoTipo.all
    @cargos = Cargo.where(:alumno_id => @alumno.id)
    @pagos = Pago.where(:alumno_id => @alumno.id)
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alumno }
    end
  end

  # GET /alumnos/new
  # GET /alumnos/new.json
  def new
    @alumno = Alumno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alumno }
    end
  end

  # GET /alumnos/1/edit
  def edit
    @alumno = Alumno.find(params[:id])
  end

  # POST /alumnos
  # POST /alumnos.json
  def create
    if params[:nombre] == ""
      flash[:notice] = "Debe llenar el campo de 'Nombre'"
      correcto = false
    elsif params[:nombre][/[0-9]+/]
      flash[:notice] = "El campo 'Nombre' no debe contener numeros"
      correcto = false
    else
      @alumno = Alumno.new(:nombre => params[:nombre])
      if @alumno.save
        correcto = true
      else
        correcto = false
      end
    end

    if params[:colegiatura] == "1"
      if params[:costo_col] == ""
        flash[:notice] = "Debe establecer una cantidad para 'Colegiatura'"
        correcto = false
      elsif params[:costo_col][/[a-zA-Z]+/]
        flash[:notice] = "El campo de 'Colegiatura' no debe contener letras"
        correcto = false
      else
        cargo = CargoTipo.where(:titulo => 'Colegiatura').first
        alumno_costo_col = AlumnoCosto.new(:cantidad => params[:costo_col], :alumno_id => @alumno.id, :cargo_tipo_id => cargo.id)
        unless alumno_costo_col.save
          correcto = false
        end
      end
    end
    
    if params[:por_hora] == "1"
      if params[:costo_phora] == ""
        flash[:notice] = "Debe establecer una cantidad para 'Por Hora'"
        correcto = false
      elsif params[:costo_phora][/[a-zA-Z]+/]
        flash[:notice] = "El campo de 'Por Hora' no debe contener letras"
        correcto = false
      else
        cargo2 = CargoTipo.where(:titulo => "Por Hora").first
        alumno_costo_phr = AlumnoCosto.new(:cantidad => params[:costo_phora], :alumno_id => @alumno.id, :cargo_tipo_id => cargo2.id)
        unless alumno_costo_phr.save
          correcto = false
        end
      end
      
    end

    respond_to do |format|
      if correcto == true
        flash[:success] = 'El Alumno fue creado correctamente'
        format.html { redirect_to @alumno }
        format.json { render json: @alumno, status: :created, location: @alumno }
      else
        if @alumno != nil
          @alumno.destroy
        end
        format.html { render action: "new" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alumnos/1
  # PUT /alumnos/1.json
  def update
    @alumno = Alumno.find(params[:id])
    if params[:nombre] == ""
      flash[:notice] = "Debe llenar el campo de 'Nombre'"
      correcto = false
    elsif params[:nombre][/[0-9]+/]
      flash[:notice] = "El campo 'Nombre' no debe contener numeros"
      correcto = false
    else
      @alumno.nombre = params[:nombre]
      correcto = true
    end
    
    if params[:colegiatura] != nil
      if params[:costo_col] == ""
        flash[:notice] = "Debe establecer una cantidad para 'Colegiatura'"
        correcto = false
      elsif params[:costo_col][/[a-zA-Z]+/]
        flash[:notice] = "El campo de 'Colegiatura' no debe contener letras"
        correcto = false
      else
        cargo = CargoTipo.find_by_titulo('Colegiatura')
        alumno_costo = AlumnoCosto.find(:all, :conditions => ['alumno_id = ? AND cargo_tipo_id = ?', @alumno.id, cargo.id]).first
        if alumno_costo == nil
          alumno_costo_col = AlumnoCosto.new(:cantidad => params[:costo_col], :alumno_id => @alumno.id, :cargo_tipo_id => cargo.id)
          unless alumno_costo_col.save
            correcto = false
          end
        else
          alumno_costo.cantidad = params[:costo_col]
          unless alumno_costo.save
            correcto = false
          end
        end
      end
    else
      cargo = CargoTipo.where(:titulo => 'Colegiatura').first
      alumno_costo_col = AlumnoCosto.where(:alumno_id => @alumno.id, :cargo_tipo_id => cargo.id).first
      unless alumno_costo_col == nil
        @cargos_eliminar = Cargo.where(:alumno_id => @alumno.id, :tipo_cargo_id => cargo.id)
        @cargos_eliminar.each do |cargo_eliminar|
          cargo_eliminar.destroy
        end
        alumno_costo_col.destroy
      end
    end

    if params[:por_hora] != nil
      if params[:costo_phora] == ""
        flash[:notice] = "Debe establecer una cantidad para 'Por Hora'"
        correcto = false
      elsif params[:costo_phora][/[a-zA-Z]+/]
        flash[:notice] = "El campo de 'Por Hora' no debe contener letras"
        correcto = false
      else
        cargo2 = CargoTipo.find_by_titulo("Por Hora")
        alumno_costo = AlumnoCosto.find(:all, :conditions => ['alumno_id = ? AND cargo_tipo_id = ?', @alumno.id, cargo2.id]).first
        if alumno_costo == nil
          alumno_costo_phr_new = AlumnoCosto.new(:cantidad => params[:costo_phora], :alumno_id => @alumno.id, :cargo_tipo_id => cargo2.id)
          unless alumno_costo_phr_new.save
            correcto = false
          end
        else
          alumno_costo.cantidad = params[:costo_phora]
          unless alumno_costo.save
            correcto = false
          end
        end
      end
    else
      cargo2 = CargoTipo.where(:titulo => "Por Hora").first
      alumno_costo_phr = AlumnoCosto.where(:alumno_id => @alumno.id, :cargo_tipo_id => cargo2.id).first
      unless alumno_costo_phr == nil
        @cargos_eliminar = Cargo.where(:alumno_id => @alumno.id, :tipo_cargo_id => cargo2.id)
        @cargos_eliminar.each do |cargo_eliminar|
          cargo_eliminar.destroy
        end
        alumno_costo_phr.destroy
      end
    end

    respond_to do |format|
      if @alumno.save && (correcto == true)
        flash[:success] = 'Alumno fue actualizado Correctamente'
        format.html { redirect_to alumnos_path }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1
  # DELETE /alumnos/1.json
  def destroy
    @alumno = Alumno.find(params[:id])
    @alumno.destroy

    respond_to do |format|
      format.html { redirect_to alumnos_url }
      format.json { head :no_content }
    end
  end


  def nuevo
    @alumno = Alumno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alumno }
    end
  end

  def crear
    @alumno = Alumno.new(:nombre => params[:nombre])
    @alumno.save

    if params[:colegiatura] == "1"
      cargo = CargoTipo.where(:titulo => 'Colegiatura').first
      alumno_costo_col = AlumnoCosto.new(:cantidad => params[:costo_col], :alumno_id => @alumno.id, :cargo_tipo_id => cargo.id)
      alumno_costo_col.save
    end
    if params[:por_hora] == "1"
      cargo2 = CargoTipo.where(:titulo => "Por Hora").first
      alumno_costo_col = AlumnoCosto.new(:cantidad => params[:costo_phora], :alumno_id => @alumno.id, :cargo_tipo_id => cargo2.id)
      alumno_costo_col.save
    end
    
    
    redirect_to alumnos_url
  end

end

app/helpers/alumnos_helper.rb
module AlumnosHelper
  def es_de_col?
    cargo = CargoTipo.find_by_titulo("Colegiatura")
    id = cargo.id
    alumno_costo = AlumnoCosto.find(:all, :conditions => ['alumno_id = ? AND cargo_tipo_id = ?', @alumno.id, id]).first
    if alumno_costo == nil
      return false
    else
      return true
    end
  end

  def es_de_phr?
    cargo = CargoTipo.find_by_titulo("Por Hora")
    id = cargo.id
    alumno_costo = AlumnoCosto.find(:all, :conditions => ['alumno_id = ? AND cargo_tipo_id = ?', @alumno.id, id]).first
    if alumno_costo == nil
      return false
    else
      return true
    end
  end

  def costo_col
    cargo = CargoTipo.find_by_titulo("Colegiatura")
    id = cargo.id
    alumno_costo = AlumnoCosto.find(:all, :conditions => ['alumno_id = ? AND cargo_tipo_id = ?',@alumno.id, id]).first
    costo = alumno_costo.cantidad
    return costo
  end

  def costo_phora
    cargo = CargoTipo.find_by_titulo("Por Hora")
    id = cargo.id
    alumno_costo = AlumnoCosto.find(:all, :conditions => ['alumno_id = ? AND cargo_tipo_id = ?',@alumno.id, id]).first
    costo = alumno_costo.cantidad
    return costo
  end

  def fecha_con_formato(fecha)
    unless fecha == nil
      meses = "Enero Febrero Marzo Abril Mayo Junio Julio Agosto Septiembre Octubre Noviembre Diciembre".split(" ")
      mes = meses[fecha.month-1]
      fecha = fecha.day.to_s + "/" + mes + "/" + fecha.year.to_s
      return fecha
    end
  end

end

app/views/alumnos/_form.html.erb
<%= form_for(@alumno) do |f| %>
  <% if @alumno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno.errors.count, "error") %> prohibited this alumno from being saved:</h2>

      <ul>
      <% @alumno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    <% if es_de_col? %>
        on_col = true;
        $("#colegiatura").attr('checked', true);
        $("#colcost").show(100);
    <% else %>
        on_col = false;
        $("#colegiatura").attr('checked', false);
        $("#colcost").hide(100);
    <% end %>

    <% if es_de_phr? %>
        on_phr = true;
        $("#por_hora").attr('checked', true)
        $("#phcost").show(100);
    <% else %>
        on_phr = false;
        $("#por_hora").attr('checked', false)
        $("#phcost").hide(100);
    <% end %>

    
    $("#colegiatura").click(function(){
      if (on_col == false){
        $("#colegiatura").attr('checked', true);
        $("#colcost").show(200);
        on_col = true;
      } else {
        $("#colegiatura").attr('checked', false);
        $("#colcost").hide(200);
        on_col = false;
      }
    });

    
    $("#por_hora").click(function(){
      if (on_phr == false){
        $("#por_hora").attr('checked', true);
        $("#phcost").show(200);
        on_phr = true;
      } else {
        $("#por_hora").attr('checked', false);
        $("#phcost").hide(200);
        on_phr = false;
      }
    });

  });
</script>
<%= link_to "Lista de Alumnos", alumnos_path, :class => "btn btn-small btn-info right" %>
<h1>Editando a Alumno</h1>

<%= form_tag(alumno_path(@alumno), :method => "put", :class => "form-horizontal") do %>
<div class="control-group">
  <div class="control-label"><%= label_tag "Nombre" %></div>
  <div class="controls"><%= text_field_tag 'nombre', @alumno.nombre %></div>
</div>
<div id="azul">
<div class="control-group">
  <div class="control-label"><%= label_tag "Colegiatura" %></div>
  <div class="controls"><%= check_box_tag "colegiatura", '1' %></div>
</div>
<div class="control-group" id="colcost">
  <div class="control-label"<%= label_tag "Costo" %></div>
    <% if es_de_col? %>
      <div class="controls"><%= number_field_tag "costo_col", costo_col %></div>
    <% else %>
      <div class="controls"><%= number_field_tag "costo_col"%></div>
    <% end %>
</div>
</div>
<div id="verde">
<div class="control-group">
  <div class="control-label"><%= label_tag "Por Hora" %></div>
  <div class="controls"><%= check_box_tag "por_hora", '1' %></div>
</div>
<div class="control-group" id="phcost" >
  <div class="control-label"><%= label_tag "Costo" %></div>
    <% if es_de_phr? %>
      <div class="controls"><%= number_field_tag "costo_phora", costo_phora %></div>
    <% else %>
      <div class="controls"><%= number_field_tag "costo_phora" %></div>
    <% end %>
</div>
</div>
<div class="control-group" style="margin-top: 10px;">
  <div class="controls"><%= submit_tag "Guardar Alumno", :class => "btn" %></div>
</div>
<% end %>

app/views/alumnos/index.html.erb
<% @cargotipos.each do |cargotipo| %>
  <%= link_to "Alumnos de " + cargotipo.titulo, cargo_alumnos_path(cargotipo.id), :class => "btn btn-small btn-info" %>
<% end %>
<h1>Lista de Alumnos</h1>
<% if @alumnos.empty? %>
<% else %>
<table class="table table-bordered table-hover table-condensed">
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alumnos.each do |alumno| %>
  
  <tr>
    <td><%= alumno.nombre %></td>
    <td><%= link_to 'Detalles', alumno, :class => "btn btn-small btn-info" %></td>
    <td><%= link_to 'Editar', edit_alumno_path(alumno), :class => "btn btn-small btn-warning" %></td>
    <td><%= link_to 'Eliminar', alumno, confirm: 'Are you sure?', method: :delete, :class => "btn btn-small btn-danger" %></td>
  </tr>
<% end %>
</table>
<% end %>

<table class="table table-bordered table-hover table-condensed">
  <tr>
    <th>Alumo_costo ID</th>
    <th>Cant</th>
    <th>Alumno_id</th>
    <th>Alumno</th>
    <th>Cargo_tipo_id</th>
    <th>Cargo_tipo</th>
  </tr>

<% @alumno_costos.each do |alumno_costo| %>
  <tr>
    <td><%= alumno_costo.id %></td>
    <td><%= alumno_costo.cantidad %></td>
    <td><%= alumno_costo.alumno_id %></td>
    <td><%= alumno_costo.alumno.nombre %></td>
    <td><%= alumno_costo.cargo_tipo_id %></td>
    <td><%= alumno_costo.cargo_tipo.titulo %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'Crear Alumno', new_alumno_path, :class => "btn" %><br/>

app/views/alumnos/new.html.erb
<script type="text/javascript">
  $(document).ready(function(){
    $("#colegiatura").attr('checked', false);
    $("#por_hora").attr('checked', false);
    $("#phcost").hide(100);
    $("#colcost").hide(100);
    var on_col = false
    $("#colegiatura").click(function(){
      if (on_col == false){
        $("#colegiatura").attr('checked', true);
        $("#colcost").show(200);
        on_col = true;
      } else {
        $("#colegiatura").attr('checked', false);
        $("#colcost").hide(200);
        on_col = false
      }
    });
    
    var on_phr = false
    $("#por_hora").click(function(){
      if (on_phr == false){
        $("#por_hora").attr('checked', true);
        $("#phcost").show(200);
        on_phr = true;
      } else {
        $("#por_hora").attr('checked', false);
        $("#phcost").hide(200);
        on_phr = false
      }
    });
  });
</script>
<h1>Nuevo Alumno</h1>

<%= form_tag(alumnos_path, :method => "post", :name => "alumno_new", :class => "form-horizontal") do %>
  <div class="control-group">
    <div class="control-label"><%= label_tag "Nombre" %></div>
    <div class="controls"><%= text_field_tag 'nombre' %></div>
  </div>
  <div id="azul">
  <div class="control-group">
    <div class="control-label"><%= label_tag "Colegiatura" %></div>
    <div class="controls"><%= check_box_tag "colegiatura", '1', :id => "colegiatura" %></div>
  </div>
  <div class="control-group" id="colcost">
    <div class="control-label"<%= label_tag "Costo" %></div>
    <div class="controls"><%= number_field_tag "costo_col", "" %></div>
  </div>
  </div>
  <div id="verde">
  <div class="control-group">
    <div class="control-label"><%= label_tag "Por Hora" %></div>
    <div class="controls"><%= check_box_tag "por_hora", '1', :id => "por_hora" %></div>
  </div>
  <div class="control-group" id="phcost">
    <div class="control-label"><%= label_tag "Costo" %></div>
    <div class="controls"><%= number_field_tag "costo_phora" %></div>
  </div>
  </div>
  <div class="control-group" style="margin-top: 10px;">
    <div class="controls"><%= submit_tag "Guardar Alumno", :class => "btn btn-success" %></div>
  </div>
<% end %>

app/views/alumnos/nuevo.html.erb
<h1>Nuevo Alumno</h1>
<table class="table">
<%= form_tag(crear_alumno_path, :method => "post") do %>
  <tr>
    <td><%= label_tag "Nombre" %></td>
    <td><%= text_field_tag 'nombre' %></td>
  </tr>
  <tr>
    <td><%= label_tag "Colegiatura" %></td>
    <td><%= check_box_tag "colegiatura", '1' %></td>
  </tr>
  <tr id="colcost">
    <td><%= label_tag "Costo" %></td>
    <td><%= number_field_tag "costo_col" %></td>
  </tr>
  <tr>
    <td><%= label_tag "Por Hora" %></td>
    <td><%= check_box_tag "por_hora", '1' %></td>
  </tr>
  <tr id="phcost">
    <td><%= label_tag "Costo" %></td>
    <td><%= number_field_tag "costo_phora" %></td>
  </tr>
  <tr>
    <td><%= submit_tag "Guardar Alumno", :class => "btn" %></td>
    <td></td>
  </tr>
<% end %>
</table>

app/views/alumnos/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><%= @alumno.nombre %></h1><br/>
  <table class="table table-bordered table-hover table-condensed">
    <tr>
  <% @alumno_costos.each do |alumno_costo| %>
    
      <th><%= alumno_costo.cargo_tipo.titulo %></th>
    
  <% end %>
    </tr>
    <tr>
  <% @alumno_costos.each do |alumno_costo| %>
      <td><%= alumno_costo.cantidad %></td>
  <% end %>
    </tr>
  </table>

  <% unless @cargos == nil %>
    <% total_cargos = 0 %>
    <% @cargos.each do |cargo| %>
      <% total_cargos += cargo.cantidad %>
    <% end %>
    <div style="width: 100%; text-align: right;">Total de Cargos = <%= total_cargos %></div>
  <% end %>

  <% unless @pagos == nil %>
    <% total_pagos = 0 %>
    <% @pagos.each do |pago| %>
      <% total_pagos += pago.cantidad %>
    <% end %>
    <div style="width: 100%; text-align: right;">Total de Pagos = <%= total_pagos %></div>
  <% end %>

  <div style="width: 100%; text-align: right; font-weight: bold;">El alumno debe = <%= total_cargos - total_pagos %></div>
  

<%= link_to 'Lista de Alumnos', alumnos_path, :class => "btn btn-small btn-info" %> |
<%= link_to 'Editar', edit_alumno_path(@alumno), :class => "btn btn-small btn-warning" %>