config/routes.rb
SistemaPagos::Application.routes.draw do
  resources :users

  root :to => "Alumnos#index"

  resources :cargos

  resources :pagos

  resources :alumno_costos

  resources :cargo_tipos

  resources :alumnos

  resource  :user_session, :only => [:new, :create, :destroy]

  delete "logout" => "user_sessions#destroy", :as => :logout

  match "sign_in" => "user_sessions#new", :as => :signin

  get "alumno/nuevo" => "alumnos#nuevo", :as => :nuevo_alumno

  post "alumno/crear" => "alumnos#crear", :as => :crear_alumno

  match "alumnos/cargo/:id" => "alumno_costos#index", :as => :cargo_alumnos

end

app/models/alumno_costo.rb
class AlumnoCosto < ActiveRecord::Base
  attr_accessible :cantidad, :alumno_id, :cargo_tipo_id
  
  belongs_to :alumno, :foreign_key => "alumno_id"
  belongs_to :cargo_tipo, :foreign_key => "cargo_tipo_id"

  validates :cantidad, :presence => true
  validates_uniqueness_of :alumno_id, :scope => :cargo_tipo_id
end

app/controllers/alumno_costos_controller.rb
class AlumnoCostosController < ApplicationController
  # GET /alumno_costos
  # GET /alumno_costos.json
  def index
    @cargotipos = CargoTipo.all
    if params[:id]
      @cargo = CargoTipo.find(params[:id])
      @alumno_costos = AlumnoCosto.includes(:alumno).order("alumnos.nombre ASC").where(:cargo_tipo_id => @cargo.id)
    else
      @alumno_costos = AlumnoCosto.all
    end
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @alumno_costos }
    end
  end

  # GET /alumno_costos/1
  # GET /alumno_costos/1.json
  def show
    @alumno_costo = AlumnoCosto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @alumno_costo }
    end
  end

  # GET /alumno_costos/new
  # GET /alumno_costos/new.json
  def new
    @alumno_costo = AlumnoCosto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @alumno_costo }
    end
  end

  # GET /alumno_costos/1/edit
  def edit
    @alumno_costo = AlumnoCosto.find(params[:id])
  end

  # POST /alumno_costos
  # POST /alumno_costos.json
  def create
    @alumno_costo = AlumnoCosto.new(params[:alumno_costo])

    respond_to do |format|
      if @alumno_costo.save
        format.html { redirect_to @alumno_costo, notice: 'Alumno costo was successfully created.' }
        format.json { render json: @alumno_costo, status: :created, location: @alumno_costo }
      else
        format.html { render action: "new" }
        format.json { render json: @alumno_costo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /alumno_costos/1
  # PUT /alumno_costos/1.json
  def update
    @alumno_costo = AlumnoCosto.find(params[:id])

    respond_to do |format|
      if @alumno_costo.update_attributes(params[:alumno_costo])
        format.html { redirect_to @alumno_costo, notice: 'Alumno costo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @alumno_costo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumno_costos/1
  # DELETE /alumno_costos/1.json
  def destroy
    @alumno_costo = AlumnoCosto.find(params[:id])
    @alumno_costo.destroy

    respond_to do |format|
      format.html { redirect_to alumno_costos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/alumno_costos_helper.rb
module AlumnoCostosHelper
end

app/views/alumno_costos/_form.html.erb
<%= form_for(@alumno_costo) do |f| %>
  <% if @alumno_costo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alumno_costo.errors.count, "error") %> prohibited this alumno_costo from being saved:</h2>

      <ul>
      <% @alumno_costo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :alumno_id %><br />
    <%= f.collection_select :alumno_id, Alumno.all, :id, :nombre %>
  </div>
  <div class="field">
    <%= f.label :cargo_tipo_id %><br />
    <%= f.collection_select :cargo_tipo_id, CargoTipo.all, :id, :titulo %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br />
    <%= f.text_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alumno_costos/edit.html.erb
<h1>Editing alumno_costo</h1>

<%= render 'form' %>

<%= link_to 'Show', @alumno_costo %> |
<%= link_to 'Back', alumno_costos_path %>

app/views/alumno_costos/index.html.erb
<% @cargotipos.each do |cargotipo| %>
  <%= link_to "Alumnos de " + cargotipo.titulo, cargo_alumnos_path(cargotipo.id), :class => "btn btn-small btn-info" %>
<% end %>
<%= link_to 'Lista de Alumnos', alumnos_path, :class => "btn btn-small btn-info" %>

<h1>Alumnos de <%= @cargo.titulo %></h1>

<table class="table table-bordered table-hover table-condensed">
  <tr>
    <th>Alumno</th>
    <th>Cantidad</th>
    <% if @cargo.titulo == "Por Hora" %>
    <th></th>
    <% end %>
  </tr>

<% @alumno_costos.each do |alumno_costo| %>
  <tr>
    <td><%= alumno_costo.alumno.nombre %></td>
    <td><%= alumno_costo.cantidad %></td>
    <% if @cargo.titulo == "Por Hora" %>
      <%= form_tag(cargos_path, :method => "post") do %>
        <%= hidden_field_tag "cargotipo", @cargo.id %>
        <%= hidden_field_tag "alumno", alumno_costo.alumno_id %>
        <td><%= submit_tag "Agregar Cargo", :confirm => "¿Desea crear cargo?", :class => "btn btn-success" %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>

app/views/alumno_costos/index.html_1.erb
<% @cargotipos.each do |cargotipo| %>
  <%= link_to "Alumnos de " + cargotipo.titulo, cargo_alumnos_path(cargotipo.id), :class => "btn btn-info" %>
<% end %>
<h1>Alumnos de <%= @cargo.titulo %></h1>

<table class="table table-bordered table-hover table-condensed">
  <tr>
    <th>Cantidad</th>
    <th>Alumno ID</th>
    <th>Alumno</th>
    <th>Cargo tipo ID</th>
    <th>Cargo tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @alumno_costos.each do |alumno_costo| %>
  <tr>
    <td><%= alumno_costo.cantidad %></td>
    <td><%= alumno_costo.alumno_id %></td>
    <td><%= alumno_costo.alumno.nombre %></td>
    <td><%= alumno_costo.cargo_tipo_id %></td>
    <td><%= alumno_costo.cargo_tipo.titulo %></td>
    <td><%= link_to 'Show', alumno_costo %></td>
    <td><%= link_to 'Edit', edit_alumno_costo_path(alumno_costo) %></td>
    <td><%= link_to 'Destroy', alumno_costo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Alumno costo', new_alumno_costo_path %>

app/views/alumno_costos/new.html.erb
<h1>New alumno_costo</h1>

<%= render 'form' %>

<%= link_to 'Back', alumno_costos_path %>

app/views/alumno_costos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cantidad:</b>
  <%= @alumno_costo.cantidad %>
</p>

<p>
  <b>Alumno:</b>
  <%= @alumno_costo.alumno_id %>
</p>

<p>
  <b>Cargo tipo:</b>
  <%= @alumno_costo.cargo_tipo_id %>
</p>


<%= link_to 'Edit', edit_alumno_costo_path(@alumno_costo) %> |
<%= link_to 'Back', alumno_costos_path %>