config/routes.rb
SistemaPagos::Application.routes.draw do
  resources :users

  root :to => "Alumnos#index"

  resources :cargos

  resources :pagos

  resources :alumno_costos

  resources :cargo_tipos

  resources :alumnos

  resource  :user_session, :only => [:new, :create, :destroy]

  delete "logout" => "user_sessions#destroy", :as => :logout

  match "sign_in" => "user_sessions#new", :as => :signin

  get "alumno/nuevo" => "alumnos#nuevo", :as => :nuevo_alumno

  post "alumno/crear" => "alumnos#crear", :as => :crear_alumno

  match "alumnos/cargo/:id" => "alumno_costos#index", :as => :cargo_alumnos

end

app/models/cargo_tipo.rb
class CargoTipo < ActiveRecord::Base
  attr_accessible :titulo

  has_many :alumno_costos, :foreign_key => "cargo_tipo_id"
  validate :titulo, :uniqueness => true
end

app/controllers/cargo_tipos_controller.rb
class CargoTiposController < ApplicationController
  # GET /cargo_tipos
  # GET /cargo_tipos.json
  def index
    @cargo_tipos = CargoTipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cargo_tipos }
    end
  end

  # GET /cargo_tipos/1
  # GET /cargo_tipos/1.json
  def show
    @cargo_tipo = CargoTipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cargo_tipo }
    end
  end

  # GET /cargo_tipos/new
  # GET /cargo_tipos/new.json
  def new
    @cargo_tipo = CargoTipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cargo_tipo }
    end
  end

  # GET /cargo_tipos/1/edit
  def edit
    @cargo_tipo = CargoTipo.find(params[:id])
  end

  # POST /cargo_tipos
  # POST /cargo_tipos.json
  def create
    @cargo_tipo = CargoTipo.new(params[:cargo_tipo])

    respond_to do |format|
      if @cargo_tipo.save
        format.html { redirect_to @cargo_tipo, notice: 'Cargo tipo was successfully created.' }
        format.json { render json: @cargo_tipo, status: :created, location: @cargo_tipo }
      else
        format.html { render action: "new" }
        format.json { render json: @cargo_tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cargo_tipos/1
  # PUT /cargo_tipos/1.json
  def update
    @cargo_tipo = CargoTipo.find(params[:id])

    respond_to do |format|
      if @cargo_tipo.update_attributes(params[:cargo_tipo])
        format.html { redirect_to @cargo_tipo, notice: 'Cargo tipo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cargo_tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargo_tipos/1
  # DELETE /cargo_tipos/1.json
  def destroy
    @cargo_tipo = CargoTipo.find(params[:id])
    @cargo_tipo.destroy

    respond_to do |format|
      format.html { redirect_to cargo_tipos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cargo_tipos_helper.rb
module CargoTiposHelper
end

app/views/cargo_tipos/_form.html.erb
<%= form_for(@cargo_tipo) do |f| %>
  <% if @cargo_tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo_tipo.errors.count, "error") %> prohibited this cargo_tipo from being saved:</h2>

      <ul>
      <% @cargo_tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargo_tipos/edit.html.erb
<h1>Editing cargo_tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo_tipo %> |
<%= link_to 'Back', cargo_tipos_path %>

app/views/cargo_tipos/index.html.erb
<h1>Listing cargo_tipos</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Titulo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cargo_tipos.each do |cargo_tipo| %>
  <tr>
    <td><%= cargo_tipo.id %></td>
    <td><%= cargo_tipo.titulo %></td>
    <td><%= link_to 'Show', cargo_tipo %></td>
    <td><%= link_to 'Edit', edit_cargo_tipo_path(cargo_tipo) %></td>
    <td><%= link_to 'Destroy', cargo_tipo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cargo tipo', new_cargo_tipo_path %>

app/views/cargo_tipos/new.html.erb
<h1>New cargo_tipo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargo_tipos_path %>

app/views/cargo_tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Titulo:</b>
  <%= @cargo_tipo.titulo %>
</p>


<%= link_to 'Edit', edit_cargo_tipo_path(@cargo_tipo) %> |
<%= link_to 'Back', cargo_tipos_path %>