config/routes.rb
SistemaPagos::Application.routes.draw do
  resources :users

  root :to => "Alumnos#index"

  resources :cargos

  resources :pagos

  resources :alumno_costos

  resources :cargo_tipos

  resources :alumnos

  resource  :user_session, :only => [:new, :create, :destroy]

  delete "logout" => "user_sessions#destroy", :as => :logout

  match "sign_in" => "user_sessions#new", :as => :signin

  get "alumno/nuevo" => "alumnos#nuevo", :as => :nuevo_alumno

  post "alumno/crear" => "alumnos#crear", :as => :crear_alumno

  match "alumnos/cargo/:id" => "alumno_costos#index", :as => :cargo_alumnos

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SistemaPagos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" >
    /*$(document).ready(function(){
    
    });*/
  </script>
</head>
<body>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <nav>
        <% if current_user_session %>
        <ul class="nav pull-right" id="barra-superior">
          <li><%= link_to 'Alumnos', alumnos_path %></li>
          <li><%= link_to 'Cargos', cargos_path %></li>
          <li><%= link_to 'Pagos', pagos_path %></li>
          <li><%= link_to "Cerrar Sesión", logout_path, :method => "delete" %></li>
        </ul>
        <% end %>
      </nav>
    </div>
  </div>
</header>
<% flash.each do |key, value| %>
  <div id="flash" class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div id="content">
<%= yield %>
</div>
</body>
</html>